apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: portfolio-image
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: portfolio-image
  filterTags:
    pattern: '^v?(?P<version>[0-9]+\.[0-9]+\.[0-9]+)$'
    extract: '$version'
  policy:
    semver:
      range: '>=1.0.0'