apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: portfolio-image
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: portfolio-image
  policy:
    alphabetical:
      order: asc