apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: portfolio-image
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: portfolio-image
  policy:
    alphabetical:
      order: asc
  filterTags:
    pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'