apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-deployment
  namespace: flux-system
spec:
  interval: 5m
  retryInterval: 2m
  timeout: 3m
  prune: true
  path: ./deployments/docs
  sourceRef:
    kind: GitRepository
    name: flux-system