apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: docs-image
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: docs-image
  filterTags:
    pattern: '^(?P<version>[0-9]+\.[0-9]+\.[0-9]+)$'
    extract: '$version'
  policy:
    semver:
      range: '>=0.1.0'