---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik
  namespace: default
  labels:
    app: authentik
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentik
  template:
    metadata:
      labels:
        app: authentik
    spec:
      containers:
        - name: server
          image: ghcr.io/goauthentik/server
          ports:
            - containerPort: 9000
            - containerPort: 9443
          env:
            - name: AUTHENTIK_POSTGRESQL__HOST
              value: 192.168.1.76:5432
            - name: AUTHENTIK_POSTGRESQL__NAME
              value: authentik
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              value: xvV/cH15xDKaXMriH+pKHOTy49rWb43tT4aB/NAW5RPViRmw
            - name: AUTHENTIK_POSTGRESQL__USER
              value: DB
            - name: AUTHENTIK_SECRET_KEY
              value: /7MLtuauVYEnL9tmU0FgLCINrs1f3R5M+IG3bMTXGGekQiR1uswlB+9/QbKsyARs+01cYlkjS4P/IOlS
        - name: worker
          image: ghcr.io/goauthentik/server
          env:
            - name: AUTHENTIK_POSTGRESQL__HOST
              value: 192.168.1.76:5432
            - name: AUTHENTIK_POSTGRESQL__NAME
              value: authentik
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              value: xvV/cH15xDKaXMriH+pKHOTy49rWb43tT4aB/NAW5RPViRmw
            - name: AUTHENTIK_POSTGRESQL__USER
              value: DB
            - name: AUTHENTIK_SECRET_KEY
              value: /7MLtuauVYEnL9tmU0FgLCINrs1f3R5M+IG3bMTXGGekQiR1uswlB+9/QbKsyARs+01cYlkjS4P/IOlS
      volumes:
        - name: authentik-data-data
          hostPath:
            path: /data
            type: Directory
        - name: authentik-data-templates
          hostPath:
            path: /templates
            type: Directory
        - name: authentik-data-certs
          hostPath:
            path: /certs
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: authetik-service
  namespace: default
spec:
  selector:
    app: server
  ports:
    - name: authetntik-port
      port: 80
      targetPort: 9000

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-data-longhorn
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 3Gi
