authentik:
    secret_key: "qCLwIn6jBg1xApWekt5Bl5TwZniEO7cROBvS1I9cPd/WYBso"
    # This sends anonymous usage-data, stack traces on errors and
    # performance data to sentry.io, and is fully opt-in
    error_reporting:
        enabled: true
    postgresql:
        password: "UfHzsUIfFFrUKZVb2GBlSnBT5yjoaVXkF4xQMO83qkEpxVVyet"

server:
    ingress:
        # Specify kubernetes ingress controller class name
        ingressClassName: traefik
        enabled: true
        hosts:
            - auth.gyurus.hu

postgresql:
    enabled: true
    auth:
        password: "UfHzsUIfFFrUKZVb2GBlSnBT5yjoaVXkF4xQMO83qkEpxVVyet"
